import swys from "../images/dummy/swys.png";
import chrome from "../images/dummy/chrome.png";
import shaggi from "../images/dummy/shaggi.png";
import ye from "../images/dummy/ye.png";

export const albums = [
	{
		image: swys,
		name: "SWYS: ISSAC",
	},
	{
		image: chrome,
		name: "CHROME: Zinoleesky",
	},
	{
		image: ye,
		name: "YE: Burna Boy",
	},
	{
		image: shaggi,
		name: "Happy Day: Shaggi",
	},
	{
		image: swys,
		name: "SWYS: ISSAC",
	},
	{
		image: chrome,
		name: "CHROME: Zinoleesky",
	},
	{
		image: ye,
		name: "YE: Burna Boy",
	},
	{
		image: shaggi,
		name: "Happy Day: Shaggi",
	},
];

export const genres = [
	"12-bar blues",
	"2 tone",
	"2-step garage",
	"4-beat",
	"50s progression",
	"a cappella",
	"accordion",
	"acid breaks",
	"acid house",
	"acid jazz",
	"acid rock",
	"acid techno",
	"acid trance",
	"acousmatic music",
	"acoustic",
	"adult contemporary",
	"african",
	"african blues",
	"african heavy metal",
	"african hip hop",
	"african-american",
	"afro cosmic disco",
	"afro-cuban jazz",
	"afrobeat",
	"afropop",
	"aggrotech",
	"aleatoric",
	"algerian",
	"alternative",
	"alternative country",
	"alternative dance",
	"alternative hip hop",
	"alternative metal",
	"alternative r&b",
	"alternative rock",
	"amami islands",
	"ambient",
	"ambient dub",
	"ambient house",
	"ambient music",
	"american folk revival",
	"americana",
	"anarchist",
	"anarcho punk",
	"anarcho-punk",
	"anasheed",
	"anatolian rock",
	"ancient",
	"anime",
	"anti-folk",
	"apala",
	"appalachian folk music",
	"arab pop",
	"arabic pop",
	"argentine rock",
	"ars antiqua",
	"ars nova",
	"ars subtilior",
	"art pop",
	"art punk",
	"art rock",
	"ashik",
	"asian",
	"asian american jazz",
	"asian underground",
	"assyrian pop music",
	"atlanta hip hop",
	"australian aboriginal",
	"australian country",
	"australian country music",
	"australian hip hop",
	"australian pub rock",
	"austropop",
	"avant-garde",
	"avant-garde jazz",
	"avant-garde metal",
	"avant-punk",
	"axé",
];
